### ISSUE TITLE
Асинхронная обработка RabbitMQ

### ISSUE THREAD

**Issue by Dominioncher** [deadokman/MicroserviceCore#11]
Есть ли возможность обрабатывать асинхронно сообщения одного и того же типа для RAbbitMQ ? 
Сейчас у меня при использовании слоя RabbitMQ HandleMessage(MessageType) Если сообщение начало обрабатываться то сервис больше не берет в работу сообщения такого же типа

**Comment by deadokman** [comment]
Я бы сказал, что формально это возможно, но так работать не должно на мой взгляд. 
Причин несколько:
  1) Если хочется за раз получить (зарезервировать) сразу больше сообщений из очереди - можно воспользоваться опцией PrefetchCount.
 2) Субъективно я бы сказал, что чем меньше кода работает "параллельно" или асинхронно, тем лучше для разработчиков и поддержки приложения. Моё мнение, если асинхронность для сообщений одного типа нужна для повышения скорости обработки, то должны быть горизонтально отмасштабированы сами службы обработки, средствами Kubernetes Horizontal Pod Autoscaler или любыми другими.

**Comment by deadokman** [comment]
> Есть ли возможность обрабатывать асинхронно сообщения одного и того же типа для RAbbitMQ ?
> Сейчас у меня при использовании слоя RabbitMQ HandleMessage(MessageType) Если сообщение начало обрабатываться то сервис больше не берет в работу сообщения такого же типа

Я бы сказал, что формально это возможно, но так работать не должно на мой взгляд.
Причин несколько:

1) Если хочется за раз получить (зарезервировать) сразу больше сообщений из очереди - можно воспользоваться опцией PrefetchCount.
2) Субъективно я бы сказал, что чем меньше кода работает "параллельно" или асинхронно, тем лучше для разработчиков и поддержки приложения. Моё мнение, если асинхронность для сообщений одного типа нужна для повышения скорости обработки, то должны быть горизонтально отмасштабированы сами службы обработки, средствами Kubernetes Horizontal Pod Autoscaler или любыми другими.
